#!/usr/bin/fish

# Theme Apply Script
# Applies a theme from themes/*.conf to all your dotfiles
#
# Usage:
#   ./theme-apply.fish <theme-name>
#   ./theme-apply.fish hamblue
#   ./theme-apply.fish --list
#   ./theme-apply.fish --current

set -l SCRIPT_DIR (dirname (realpath (status filename)))
set -l THEMES_DIR "$SCRIPT_DIR/themes"
set -l CURRENT_THEME_FILE "$SCRIPT_DIR/themes/.current-theme"

# Color output helpers
function log_info
    set_color cyan; echo ":: $argv"; set_color normal
end

function log_success
    set_color green; echo "✓ $argv"; set_color normal
end

function log_warn
    set_color yellow; echo "! $argv"; set_color normal
end

function log_error
    set_color red; echo "✗ $argv"; set_color normal
end

# Show help
function show_help
    echo "Theme Apply - Unified theme management for dotfiles"
    echo ""
    echo "Usage:"
    echo "  theme-apply.fish <theme-name>    Apply a theme"
    echo "  theme-apply.fish --list          List available themes"
    echo "  theme-apply.fish --current       Show current theme"
    echo "  theme-apply.fish --help          Show this help"
    echo ""
    echo "Available themes:"
    for theme in $THEMES_DIR/*.conf
        set -l name (basename $theme .conf)
        set -l desc (grep -m1 '^#' $theme | sed 's/^# *//')
        printf "  %-12s %s\n" $name "$desc"
    end
end

# List themes
function list_themes
    echo "Available themes in $THEMES_DIR:"
    echo ""
    for theme in $THEMES_DIR/*.conf
        set -l name (basename $theme .conf)
        set -l desc (grep -m1 '^#' $theme | sed 's/^# *//')
        set -l current ""
        if test -f $CURRENT_THEME_FILE
            if test (cat $CURRENT_THEME_FILE) = $name
                set current " (current)"
            end
        end
        printf "  %-12s %s%s\n" $name "$desc" "$current"
    end
end

# Show current theme
function show_current
    if test -f $CURRENT_THEME_FILE
        echo (cat $CURRENT_THEME_FILE)
    else
        echo "No theme currently set"
        return 1
    end
end

# Parse theme file and load colors into variables
function load_theme
    set -l theme_file $argv[1]

    if not test -f $theme_file
        log_error "Theme file not found: $theme_file"
        return 1
    end

    # First pass: load raw values
    for line in (grep -v '^#' $theme_file | grep -v '^$' | grep '=')
        set -l key (echo $line | cut -d'=' -f1)
        set -l value (echo $line | cut -d'=' -f2-)
        set -g "THEME_$key" $value
    end

    # Second pass: resolve variable references
    for line in (grep -v '^#' $theme_file | grep -v '^$' | grep '=')
        set -l key (echo $line | cut -d'=' -f1)
        set -l value (echo $line | cut -d'=' -f2-)

        # If value starts with $, resolve it
        if string match -q '$*' $value
            set -l ref_key (string replace '$' '' $value)
            set -l ref_var "THEME_$ref_key"
            if set -q $ref_var
                set -g "THEME_$key" $$ref_var
            end
        end
    end

    return 0
end

# Get a theme color (returns without #)
function get_color
    set -l var "THEME_$argv[1]"
    if set -q $var
        echo $$var
    else
        log_warn "Color not found: $argv[1]"
        echo "000000"
    end
end

# Update Hyprland theme
function apply_hyprland
    set -l hypr_theme "$HOME/.config/hypr/themes/current.conf"

    log_info "Applying to Hyprland..."

    mkdir -p (dirname $hypr_theme)

    # Create/update the current theme file
    echo "# Auto-generated by theme-apply.fish" > $hypr_theme
    echo "# Theme: $THEME_NAME" >> $hypr_theme
    echo "" >> $hypr_theme
    echo "\$black = rgb("(get_color bg)")" >> $hypr_theme
    echo "\$darkbluegrey = rgb("(get_color dark)")" >> $hypr_theme
    echo "\$medbluegrey = rgb("(get_color medium)")" >> $hypr_theme
    echo "\$lightbluegrey = rgb("(get_color light)")" >> $hypr_theme
    echo "\$offwhite = rgb("(get_color fg)")" >> $hypr_theme

    log_success "Hyprland theme: $hypr_theme"

    # Reload hyprland if running
    if pgrep -x Hyprland > /dev/null
        hyprctl reload > /dev/null 2>&1
        log_success "Hyprland reloaded"
    end
end

# Update Foot terminal
function apply_foot
    set -l foot_config "$HOME/.config/foot/foot.ini"

    if not test -f $foot_config
        log_warn "Foot config not found, skipping"
        return
    end

    log_info "Applying to Foot..."

    # Update colors section
    sed -i "s/^foreground=.*/foreground="(get_color fg)"/" $foot_config
    sed -i "s/^background=.*/background="(get_color bg)"/" $foot_config
    sed -i "s/^regular0=.*/regular0="(get_color black)" # black/" $foot_config
    sed -i "s/^regular1=.*/regular1="(get_color red)" # red/" $foot_config
    sed -i "s/^regular2=.*/regular2="(get_color green)" # green/" $foot_config
    sed -i "s/^regular3=.*/regular3="(get_color yellow)" # yellow/" $foot_config
    sed -i "s/^regular4=.*/regular4="(get_color blue)" # blue/" $foot_config
    sed -i "s/^regular5=.*/regular5="(get_color magenta)" # magenta/" $foot_config
    sed -i "s/^regular6=.*/regular6="(get_color cyan)" # cyan/" $foot_config
    sed -i "s/^regular7=.*/regular7="(get_color white)" # white/" $foot_config
    sed -i "s/^bright0=.*/bright0="(get_color bright_black)" # bright black/" $foot_config
    sed -i "s/^bright1=.*/bright1="(get_color bright_red)" # bright red/" $foot_config
    sed -i "s/^bright2=.*/bright2="(get_color bright_green)" # bright green/" $foot_config
    sed -i "s/^bright3=.*/bright3="(get_color bright_yellow)" # bright yellow/" $foot_config
    sed -i "s/^bright4=.*/bright4="(get_color bright_blue)" # bright blue/" $foot_config
    sed -i "s/^bright5=.*/bright5="(get_color bright_magenta)" # bright magenta/" $foot_config
    sed -i "s/^bright6=.*/bright6="(get_color bright_cyan)" # bright cyan/" $foot_config
    sed -i "s/^bright7=.*/bright7="(get_color bright_white)" # bright white/" $foot_config

    log_success "Foot config updated"
end

# Update Mako notifications
function apply_mako
    set -l mako_config "$HOME/.config/mako/config"

    if not test -f $mako_config
        log_warn "Mako config not found, skipping"
        return
    end

    log_info "Applying to Mako..."

    sed -i "s/^background-color=.*/background-color=#"(get_color bg)"/" $mako_config
    sed -i "s/^text-color=.*/text-color=#"(get_color fg)"/" $mako_config
    sed -i "s/^border-color=.*/border-color=#"(get_color light)"/" $mako_config
    sed -i "s/^progress-color=.*/progress-color=over #"(get_color accent)"/" $mako_config

    # Update urgency section
    sed -i "/\[urgency=high\]/,/^$\|^\[/ s/border-color=.*/border-color=#"(get_color error)"/" $mako_config

    log_success "Mako config updated"

    # Reload mako if running
    if pgrep -x mako > /dev/null
        makoctl reload > /dev/null 2>&1
        log_success "Mako reloaded"
    end
end

# Update Waybar
function apply_waybar
    set -l waybar_style "$HOME/.config/waybar/style.css"

    if not test -f $waybar_style
        log_warn "Waybar style not found, skipping"
        return
    end

    log_info "Applying to Waybar..."

    # Create CSS variables block at top of file
    set -l css_vars "/* Theme: $THEME_NAME - Auto-generated */
:root {
  --bg: #"(get_color bg)";
  --fg: #"(get_color fg)";
  --dark: #"(get_color dark)";
  --medium: #"(get_color medium)";
  --light: #"(get_color light)";
  --accent: #"(get_color accent)";
  --surface: #"(get_color surface)";
  --error: #"(get_color error)";
  --warning: #"(get_color warning)";
  --success: #"(get_color success)";
}
"

    # Check if :root block exists
    if grep -q ':root {' $waybar_style
        # Replace existing :root block
        sed -i '/:root {/,/^}/d' $waybar_style
        sed -i '/Theme:.*Auto-generated/d' $waybar_style
    end

    # Prepend CSS variables
    echo "$css_vars" | cat - $waybar_style > /tmp/waybar_style_tmp && mv /tmp/waybar_style_tmp $waybar_style

    log_success "Waybar style updated (CSS variables injected)"
    log_warn "Note: Update your waybar CSS to use var(--bg), var(--fg), etc."

    # Reload waybar if running
    if pgrep -x waybar > /dev/null
        killall -SIGUSR2 waybar 2>/dev/null
        log_success "Waybar reloaded"
    end
end

# Update Starship prompt
function apply_starship
    set -l starship_config "$HOME/.config/starship.toml"

    if not test -f $starship_config
        log_warn "Starship config not found, skipping"
        return
    end

    log_info "Applying to Starship..."

    # Update the palette line
    sed -i "s/^palette=.*/palette=\"$THEME_NAME\"/" $starship_config

    # Check if palette exists, if not add it
    if not grep -q "^\[palettes.$THEME_NAME\]" $starship_config
        log_info "Adding $THEME_NAME palette to starship.toml..."

        echo "" >> $starship_config
        echo "[palettes.$THEME_NAME]" >> $starship_config
        echo "color_fg = \"#"(get_color fg)"\"" >> $starship_config
        echo "color_bg = \"#"(get_color bg)"\"" >> $starship_config
        echo "color_0 = \"#"(get_color bg)"\"" >> $starship_config
        echo "color_1 = \"#"(get_color dark)"\"" >> $starship_config
        echo "color_2 = \"#"(get_color medium)"\"" >> $starship_config
        echo "color_3 = \"#"(get_color light)"\"" >> $starship_config
        echo "color_4 = \"#"(get_color fg)"\"" >> $starship_config
        echo "color_5 = \"#"(get_color dark)"\"" >> $starship_config
        echo "color_6 = \"#"(get_color light)"\"" >> $starship_config
        echo "color_7 = \"#"(get_color fg)"\"" >> $starship_config
        echo "cambridgeblue = \"#"(get_color light)"\"" >> $starship_config
    else
        log_info "Updating existing $THEME_NAME palette..."
        # Update existing palette values
        sed -i "/^\[palettes.$THEME_NAME\]/,/^\[/ {
            s/color_fg = .*/color_fg = \"#"(get_color fg)"\"/
            s/color_bg = .*/color_bg = \"#"(get_color bg)"\"/
            s/color_0 = .*/color_0 = \"#"(get_color bg)"\"/
            s/color_1 = .*/color_1 = \"#"(get_color dark)"\"/
            s/color_2 = .*/color_2 = \"#"(get_color medium)"\"/
            s/color_3 = .*/color_3 = \"#"(get_color light)"\"/
            s/color_4 = .*/color_4 = \"#"(get_color fg)"\"/
            s/cambridgeblue = .*/cambridgeblue = \"#"(get_color light)"\"/
        }" $starship_config
    end

    log_success "Starship config updated"
end

# Update Fish shell colors
function apply_fish
    set -l fish_theme "$HOME/.config/fish/conf.d/theme.fish"

    log_info "Applying to Fish..."

    mkdir -p (dirname $fish_theme)

    echo "# Theme: $THEME_NAME - Auto-generated by theme-apply.fish" > $fish_theme
    echo "" >> $fish_theme
    echo "# LS_COLORS" >> $fish_theme
    echo "set -x LS_COLORS \"di=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color light)) 0x(string sub -s 3 -l 2 (get_color light)) 0x(string sub -s 5 (get_color light)))":fi=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color fg)) 0x(string sub -s 3 -l 2 (get_color fg)) 0x(string sub -s 5 (get_color fg)))":ln=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color cyan)) 0x(string sub -s 3 -l 2 (get_color cyan)) 0x(string sub -s 5 (get_color cyan)))":ex=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color green)) 0x(string sub -s 3 -l 2 (get_color green)) 0x(string sub -s 5 (get_color green)))"\"" >> $fish_theme
    echo "" >> $fish_theme
    echo "# Fish colors" >> $fish_theme
    echo "set fish_color_normal \"#"(get_color fg)"\"" >> $fish_theme
    echo "set fish_color_command \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_color_comment \"#"(get_color dark)"\"" >> $fish_theme
    echo "set fish_color_keyword \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_color_quote \"#"(get_color light)"\"" >> $fish_theme
    echo "set fish_color_redirection \"#"(get_color dark)"\"" >> $fish_theme
    echo "set fish_color_end \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_color_error \"#"(get_color error)"\"" >> $fish_theme
    echo "set fish_color_selection \"#"(get_color dark)"\"" >> $fish_theme
    echo "set fish_color_search_match \"#"(get_color light)"\"" >> $fish_theme
    echo "set fish_color_operator \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_color_escape \"#"(get_color light)"\"" >> $fish_theme
    echo "set fish_color_cwd \"#"(get_color light)"\"" >> $fish_theme
    echo "set fish_color_user \"#"(get_color fg)"\"" >> $fish_theme
    echo "set fish_color_autosuggestion \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_pager_color_completion \"#"(get_color fg)"\"" >> $fish_theme
    echo "set fish_pager_color_description \"#"(get_color medium)"\"" >> $fish_theme
    echo "set fish_pager_color_prefix \"#"(get_color light)"\"" >> $fish_theme
    echo "set fish_pager_color_progress \"#"(get_color light)"\"" >> $fish_theme

    log_success "Fish theme: $fish_theme"
    log_info "Run 'source $fish_theme' or restart fish to apply"
end

# Update Neovim colorscheme
function apply_nvim
    set -l nvim_colors "$HOME/.config/nvim/lua/colors/theme.lua"

    log_info "Applying to Neovim..."

    mkdir -p (dirname $nvim_colors)

    echo "-- Theme: $THEME_NAME - Auto-generated by theme-apply.fish" > $nvim_colors
    echo "-- Source this in your nvim config or colorscheme" >> $nvim_colors
    echo "" >> $nvim_colors
    echo "local M = {}" >> $nvim_colors
    echo "" >> $nvim_colors
    echo "M.colors = {" >> $nvim_colors
    echo "    bg = \"#"(get_color bg)"\"," >> $nvim_colors
    echo "    fg = \"#"(get_color fg)"\"," >> $nvim_colors
    echo "    dark = \"#"(get_color dark)"\"," >> $nvim_colors
    echo "    medium = \"#"(get_color medium)"\"," >> $nvim_colors
    echo "    light = \"#"(get_color light)"\"," >> $nvim_colors
    echo "    accent = \"#"(get_color accent)"\"," >> $nvim_colors
    echo "    surface = \"#"(get_color surface)"\"," >> $nvim_colors
    echo "    error = \"#"(get_color error)"\"," >> $nvim_colors
    echo "    warning = \"#"(get_color warning)"\"," >> $nvim_colors
    echo "    success = \"#"(get_color success)"\"," >> $nvim_colors
    echo "    -- Terminal colors" >> $nvim_colors
    echo "    black = \"#"(get_color black)"\"," >> $nvim_colors
    echo "    red = \"#"(get_color red)"\"," >> $nvim_colors
    echo "    green = \"#"(get_color green)"\"," >> $nvim_colors
    echo "    yellow = \"#"(get_color yellow)"\"," >> $nvim_colors
    echo "    blue = \"#"(get_color blue)"\"," >> $nvim_colors
    echo "    magenta = \"#"(get_color magenta)"\"," >> $nvim_colors
    echo "    cyan = \"#"(get_color cyan)"\"," >> $nvim_colors
    echo "    white = \"#"(get_color white)"\"," >> $nvim_colors
    echo "}" >> $nvim_colors
    echo "" >> $nvim_colors
    echo "M.name = \"$THEME_NAME\"" >> $nvim_colors
    echo "" >> $nvim_colors
    echo "return M" >> $nvim_colors

    log_success "Neovim colors: $nvim_colors"
    log_info "Use: local theme = require('colors.theme') in your nvim config"
end

# Update Fuzzel launcher
function apply_fuzzel
    set -l fuzzel_config "$HOME/.config/fuzzel/fuzzel.ini"

    if not test -f $fuzzel_config
        log_warn "Fuzzel config not found, skipping"
        return
    end

    log_info "Applying to Fuzzel..."

    # Update colors section
    sed -i "/^\[colors\]/,/^\[/ {
        s/^background = .*/background = "(get_color bg)"ee/
        s/^text = .*/text = "(get_color fg)"ff/
        s/^match = .*/match = "(get_color light)"ff/
        s/^selection = .*/selection = "(get_color dark)"ff/
        s/^selection-text = .*/selection-text = "(get_color light)"ff/
        s/^border = .*/border = "(get_color medium)"ff/
        s/^separator = .*/separator = "(get_color dark)"ff/
    }" $fuzzel_config

    log_success "Fuzzel config updated"
end

# Update Rofi themes
function apply_rofi
    set -l rofi_dir "$HOME/.config/rofi"
    set -l themes_dir "$rofi_dir/themes"

    if not test -d $rofi_dir
        log_warn "Rofi config not found, skipping"
        return
    end

    log_info "Applying to Rofi..."

    # Create a generated theme file that other themes can import
    set -l generated_theme "$themes_dir/colors.rasi"
    mkdir -p $themes_dir

    echo "/* Theme: $THEME_NAME - Auto-generated by theme-apply.fish */" > $generated_theme
    echo "* {" >> $generated_theme
    echo "    theme-bg: #"(get_color bg)";" >> $generated_theme
    echo "    theme-fg: #"(get_color fg)";" >> $generated_theme
    echo "    theme-dark: #"(get_color dark)";" >> $generated_theme
    echo "    theme-medium: #"(get_color medium)";" >> $generated_theme
    echo "    theme-light: #"(get_color light)";" >> $generated_theme
    echo "    theme-accent: #"(get_color accent)";" >> $generated_theme
    echo "    theme-error: #"(get_color error)";" >> $generated_theme
    echo "    theme-warning: #"(get_color warning)";" >> $generated_theme
    echo "    theme-success: #"(get_color success)";" >> $generated_theme
    echo "    /* Convenience aliases */" >> $generated_theme
    echo "    background: #"(get_color bg)";" >> $generated_theme
    echo "    foreground: #"(get_color fg)";" >> $generated_theme
    echo "    selected: #"(get_color light)";" >> $generated_theme
    echo "}" >> $generated_theme

    log_success "Rofi colors: $generated_theme"

    # Update existing theme files if they have the simple format
    for theme_file in $themes_dir/power.rasi $themes_dir/launcher.rasi $themes_dir/clipboard.rasi
        if test -f $theme_file
            sed -i "s/background: #[0-9a-fA-F]\{6\}/background: #"(get_color bg)"/" $theme_file
            sed -i "s/foreground: #[0-9a-fA-F]\{6\}/foreground: #"(get_color fg)"/" $theme_file
            sed -i "s/selected: #[0-9a-fA-F]\{6\}/selected: #"(get_color light)"/" $theme_file
            log_success "Updated: "(basename $theme_file)
        end
    end

    log_info "Add '@import \"colors.rasi\"' to your rofi themes to use variables"
end

# Update wlogout
function apply_wlogout
    set -l wlogout_style "$HOME/.config/wlogout/style.css"

    if not test -f $wlogout_style
        log_warn "wlogout style not found, skipping"
        return
    end

    log_info "Applying to wlogout..."

    # Similar to waybar, inject CSS variables
    set -l css_vars "/* Theme: $THEME_NAME - Auto-generated */
:root {
  --bg: #"(get_color bg)";
  --fg: #"(get_color fg)";
  --dark: #"(get_color dark)";
  --light: #"(get_color light)";
  --accent: #"(get_color accent)";
}
"

    if grep -q ':root {' $wlogout_style
        sed -i '/:root {/,/^}/d' $wlogout_style
        sed -i '/Theme:.*Auto-generated/d' $wlogout_style
    end

    echo "$css_vars" | cat - $wlogout_style > /tmp/wlogout_style_tmp && mv /tmp/wlogout_style_tmp $wlogout_style

    log_success "wlogout style updated"
end

# Main function
function main
    # Parse arguments
    if test (count $argv) -eq 0
        show_help
        return 1
    end

    switch $argv[1]
        case --help -h
            show_help
            return 0
        case --list -l
            list_themes
            return 0
        case --current -c
            show_current
            return $status
        case '--*'
            log_error "Unknown option: $argv[1]"
            show_help
            return 1
    end

    set -g THEME_NAME $argv[1]
    set -l theme_file "$THEMES_DIR/$THEME_NAME.conf"

    if not test -f $theme_file
        log_error "Theme not found: $THEME_NAME"
        echo "Available themes:"
        list_themes
        return 1
    end

    echo ""
    log_info "Applying theme: $THEME_NAME"
    echo ""

    # Load theme colors
    if not load_theme $theme_file
        return 1
    end

    # Apply to all applications
    apply_hyprland
    apply_foot
    apply_mako
    apply_waybar
    apply_starship
    apply_fish
    apply_nvim
    apply_fuzzel
    apply_rofi
    apply_wlogout

    # Save current theme
    echo $THEME_NAME > $CURRENT_THEME_FILE

    echo ""
    log_success "Theme '$THEME_NAME' applied successfully!"
    echo ""
    echo "Some changes may require:"
    echo "  - Restart your terminal for full effect"
    echo "  - Run 'source ~/.config/fish/conf.d/theme.fish' for fish colors"
    echo "  - Restart nvim for editor colors"
end

main $argv
