#!/usr/bin/fish

# Theme Apply Script
# Applies a theme from themes/*.conf to all your dotfiles
#
# Usage:
#   ./theme-apply.fish <theme-name>
#   ./theme-apply.fish hamblue
#   ./theme-apply.fish --list
#   ./theme-apply.fish --current

set -g SCRIPT_DIR "$HOME/.config"
set -g THEMES_DIR "$SCRIPT_DIR/themes"
set -g CURRENT_THEME_FILE "$THEMES_DIR/.current-theme"

# Color output helpers
function log_info
    set_color cyan; echo ":: $argv"; set_color normal
end

function log_success
    set_color green; echo "✓ $argv"; set_color normal
end

function log_warn
    set_color yellow; echo "! $argv"; set_color normal
end

function log_error
    set_color red; echo "✗ $argv"; set_color normal
end

# Show help
function show_help
    echo "Theme Apply - Unified theme management for dotfiles"
    echo ""
    echo "Usage:"
    echo "  theme-apply.fish <theme-name>    Apply a theme"
    echo "  theme-apply.fish --list          List available themes"
    echo "  theme-apply.fish --current       Show current theme"
    echo "  theme-apply.fish --help          Show this help"
    echo ""
    echo "Available themes:"
    for theme in $THEMES_DIR/*.conf
        set -l name (basename $theme .conf)
        set -l desc (grep -m1 '^#' $theme | sed 's/^# *//')
        printf "  %-12s %s\n" $name "$desc"
    end
end

# List themes
function list_themes
    echo "Available themes in $THEMES_DIR:"
    echo ""
    for theme in $THEMES_DIR/*.conf
        set -l name (basename $theme .conf)
        set -l desc (grep -m1 '^#' $theme | sed 's/^# *//')
        set -l current ""
        if test -f $CURRENT_THEME_FILE
            if test (cat $CURRENT_THEME_FILE) = $name
                set current " (current)"
            end
        end
        printf "  %-12s %s%s\n" $name "$desc" "$current"
    end
end

# Show current theme
function show_current
    if test -f $CURRENT_THEME_FILE
        echo (cat $CURRENT_THEME_FILE)
    else
        echo "No theme currently set"
        return 1
    end
end

# Parse theme file and load colors into variables
function load_theme
    set -l theme_file $argv[1]

    if not test -f $theme_file
        log_error "Theme file not found: $theme_file"
        return 1
    end

    # First pass: load raw values
    for line in (grep -v '^#' $theme_file | grep -v '^$' | grep '=')
        set -l key (echo $line | cut -d'=' -f1)
        set -l value (echo $line | cut -d'=' -f2-)
        set -g "THEME_$key" $value
    end

    # Second pass: resolve variable references
    for line in (grep -v '^#' $theme_file | grep -v '^$' | grep '=')
        set -l key (echo $line | cut -d'=' -f1)
        set -l value (echo $line | cut -d'=' -f2-)

        # If value starts with $, resolve it
        if string match -q '$*' $value
            set -l ref_key (string replace '$' '' $value)
            set -l ref_var "THEME_$ref_key"
            if set -q $ref_var
                set -g "THEME_$key" $$ref_var
            end
        end
    end

    return 0
end

# Get a theme color (returns without #)
function get_color
    set -l var "THEME_$argv[1]"
    if set -q $var
        echo $$var
    else
        log_warn "Color not found: $argv[1]"
        echo "000000"
    end
end

# Update Hyprland theme
function apply_hyprland
    set -l hypr_theme "$HOME/.config/hypr/themes/current.conf"

    log_info "Applying to Hyprland..."

    mkdir -p (dirname $hypr_theme)

    # Create/update the current theme file with generic variable names
    echo "# Auto-generated by theme-apply.fish" > $hypr_theme
    echo "# Theme: $THEME_NAME" >> $hypr_theme
    echo "" >> $hypr_theme
    echo "\$theme_bg = rgb("(get_color bg)")" >> $hypr_theme
    echo "\$theme_fg = rgb("(get_color fg)")" >> $hypr_theme
    echo "\$theme_dark = rgb("(get_color dark)")" >> $hypr_theme
    echo "\$theme_medium = rgb("(get_color medium)")" >> $hypr_theme
    echo "\$theme_light = rgb("(get_color light)")" >> $hypr_theme

    log_success "Hyprland theme: $hypr_theme"

    # Reload hyprland if running
    if pgrep -x Hyprland > /dev/null
        hyprctl reload > /dev/null 2>&1
        log_success "Hyprland reloaded"
    end
end

# Update Foot terminal
function apply_foot
    set -l foot_config "$HOME/.config/foot/foot.ini"

    if not test -f $foot_config
        log_warn "Foot config not found, skipping"
        return
    end

    log_info "Applying to Foot..."

    # Update colors section
    sed -i "s/^foreground=.*/foreground="(get_color fg)"/" $foot_config
    sed -i "s/^background=.*/background="(get_color bg)"/" $foot_config
    sed -i "s/^regular0=.*/regular0="(get_color black)" # black/" $foot_config
    sed -i "s/^regular1=.*/regular1="(get_color red)" # red/" $foot_config
    sed -i "s/^regular2=.*/regular2="(get_color green)" # green/" $foot_config
    sed -i "s/^regular3=.*/regular3="(get_color yellow)" # yellow/" $foot_config
    sed -i "s/^regular4=.*/regular4="(get_color blue)" # blue/" $foot_config
    sed -i "s/^regular5=.*/regular5="(get_color magenta)" # magenta/" $foot_config
    sed -i "s/^regular6=.*/regular6="(get_color cyan)" # cyan/" $foot_config
    sed -i "s/^regular7=.*/regular7="(get_color white)" # white/" $foot_config
    sed -i "s/^bright0=.*/bright0="(get_color bright_black)" # bright black/" $foot_config
    sed -i "s/^bright1=.*/bright1="(get_color bright_red)" # bright red/" $foot_config
    sed -i "s/^bright2=.*/bright2="(get_color bright_green)" # bright green/" $foot_config
    sed -i "s/^bright3=.*/bright3="(get_color bright_yellow)" # bright yellow/" $foot_config
    sed -i "s/^bright4=.*/bright4="(get_color bright_blue)" # bright blue/" $foot_config
    sed -i "s/^bright5=.*/bright5="(get_color bright_magenta)" # bright magenta/" $foot_config
    sed -i "s/^bright6=.*/bright6="(get_color bright_cyan)" # bright cyan/" $foot_config
    sed -i "s/^bright7=.*/bright7="(get_color bright_white)" # bright white/" $foot_config

    log_success "Foot config updated"
end

# Update Mako notifications
function apply_mako
    set -l mako_config "$HOME/.config/mako/config"

    if not test -f $mako_config
        log_warn "Mako config not found, skipping"
        return
    end

    log_info "Applying to Mako..."

    sed -i "s/^background-color=.*/background-color=#"(get_color bg)"/" $mako_config
    sed -i "s/^text-color=.*/text-color=#"(get_color fg)"/" $mako_config
    sed -i "s/^border-color=.*/border-color=#"(get_color light)"/" $mako_config
    sed -i "s/^progress-color=.*/progress-color=over #"(get_color accent)"/" $mako_config

    # Update urgency section - simple approach
    sed -i '/\[urgency=high\]/,/^$/s/border-color=.*/border-color=#'"(get_color error)"'/' $mako_config

    log_success "Mako config updated"

    # Reload mako if running
    if pgrep -x mako > /dev/null
        makoctl reload > /dev/null 2>&1
        log_success "Mako reloaded"
    end
end

# Update Waybar - GTK CSS doesn't support variables, so we replace colors directly
function apply_waybar
    set -l waybar_style "$HOME/.config/waybar/style.css"

    if not test -f $waybar_style
        log_warn "Waybar style not found, skipping"
        return
    end

    log_info "Applying to Waybar..."

    # Update the comment header with current theme colors
    sed -i '1s/.*/\/* Theme: '$THEME_NAME' - Auto-generated by theme-apply.fish *\//' $waybar_style

    # Update or add colors comment
    if grep -q '^/\* Colors:' $waybar_style
        sed -i 's|^/\* Colors:.*|/* Colors: bg=#'(get_color bg)' fg=#'(get_color fg)' dark=#'(get_color dark)' medium=#'(get_color medium)' light=#'(get_color light)' */|' $waybar_style
    else
        sed -i '2i/* Colors: bg=#'(get_color bg)' fg=#'(get_color fg)' dark=#'(get_color dark)' medium=#'(get_color medium)' light=#'(get_color light)' */' $waybar_style
    end

    # Replace color values throughout the file
    # bg color (background)
    sed -i 's/background: #[0-9a-fA-F]\{6\}/background: #'(get_color bg)'/g' $waybar_style

    # fg color (main text)
    sed -i '/window#waybar/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color fg)'/' $waybar_style

    # workspace buttons
    sed -i '/#workspaces button\s*{/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color medium)'/' $waybar_style
    sed -i '/#workspaces button\.empty/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color dark)'/' $waybar_style
    sed -i '/#workspaces button\.active/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color light)'/' $waybar_style
    sed -i '/#workspaces button\.urgent/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color error)'/' $waybar_style

    # window and mpris
    sed -i '/#window\s*{/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color medium)'/' $waybar_style
    sed -i '/#mpris\s*{/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color medium)'/' $waybar_style

    # clock highlight
    sed -i '/#clock\s*{/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color light)'/' $waybar_style

    # tooltip
    sed -i '/tooltip\s*{/,/\}/s/background: #[0-9a-fA-F]\{6\}/background: #'(get_color dark)'/' $waybar_style
    sed -i '/tooltip\s*{/,/\}/s/color: #[0-9a-fA-F]\{6\}/color: #'(get_color fg)'/' $waybar_style

    log_success "Waybar style updated"

    # Reload waybar if running - kill and restart
    if pgrep -x waybar > /dev/null
        killall waybar 2>/dev/null
        sleep 0.5
        waybar &
        disown
        log_success "Waybar restarted"
    end
end

# Update Starship prompt
function apply_starship
    set -l starship_config "$HOME/.config/starship.toml"

    if not test -f $starship_config
        log_warn "Starship config not found, skipping"
        return
    end

    log_info "Applying to Starship..."

    # Update the palette line
    sed -i "s/^palette=.*/palette=\"$THEME_NAME\"/" $starship_config

    # Check if palette exists, if not add it
    if not grep -q "^\[palettes.$THEME_NAME\]" $starship_config
        log_info "Adding $THEME_NAME palette to starship.toml..."

        echo "" >> $starship_config
        echo "[palettes.$THEME_NAME]" >> $starship_config
        echo "color_fg = \"#"(get_color fg)"\"" >> $starship_config
        echo "color_bg = \"#"(get_color bg)"\"" >> $starship_config
        echo "color_0 = \"#"(get_color bg)"\"" >> $starship_config
        echo "color_1 = \"#"(get_color dark)"\"" >> $starship_config
        echo "color_2 = \"#"(get_color medium)"\"" >> $starship_config
        echo "color_3 = \"#"(get_color light)"\"" >> $starship_config
        echo "color_4 = \"#"(get_color fg)"\"" >> $starship_config
        echo "color_5 = \"#"(get_color dark)"\"" >> $starship_config
        echo "color_6 = \"#"(get_color light)"\"" >> $starship_config
        echo "color_7 = \"#"(get_color fg)"\"" >> $starship_config
        echo "cambridgeblue = \"#"(get_color light)"\"" >> $starship_config
    else
        log_info "Updating existing $THEME_NAME palette..."
        # Update existing palette values
        sed -i "/^\[palettes.$THEME_NAME\]/,/^\[/ {
            s/color_fg = .*/color_fg = \"#"(get_color fg)"\"/
            s/color_bg = .*/color_bg = \"#"(get_color bg)"\"/
            s/color_0 = .*/color_0 = \"#"(get_color bg)"\"/
            s/color_1 = .*/color_1 = \"#"(get_color dark)"\"/
            s/color_2 = .*/color_2 = \"#"(get_color medium)"\"/
            s/color_3 = .*/color_3 = \"#"(get_color light)"\"/
            s/color_4 = .*/color_4 = \"#"(get_color fg)"\"/
            s/cambridgeblue = .*/cambridgeblue = \"#"(get_color light)"\"/
        }" $starship_config
    end

    log_success "Starship config updated"
end

# Update Fish shell colors
function apply_fish
    set -l fish_theme "$HOME/.config/fish/themes/current.fish"

    log_info "Applying to Fish..."

    mkdir -p (dirname $fish_theme)

    echo "# Theme: $THEME_NAME - Auto-generated by theme-apply.fish" > $fish_theme
    echo "" >> $fish_theme
    echo "# LS_COLORS" >> $fish_theme
    echo "set -x LS_COLORS \"di=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color light)) 0x(string sub -s 3 -l 2 (get_color light)) 0x(string sub -s 5 (get_color light)))":fi=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color fg)) 0x(string sub -s 3 -l 2 (get_color fg)) 0x(string sub -s 5 (get_color fg)))":ln=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color cyan)) 0x(string sub -s 3 -l 2 (get_color cyan)) 0x(string sub -s 5 (get_color cyan)))":ex=38;2;"(printf '%d;%d;%d' 0x(string sub -l 2 (get_color green)) 0x(string sub -s 3 -l 2 (get_color green)) 0x(string sub -s 5 (get_color green)))"\"" >> $fish_theme
    echo "" >> $fish_theme
    echo "# Fish colors (using -g to override fish_frozen_theme)" >> $fish_theme
    echo "set -g fish_color_normal \"#"(get_color fg)"\"" >> $fish_theme
    echo "set -g fish_color_command \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_color_comment \"#"(get_color dark)"\"" >> $fish_theme
    echo "set -g fish_color_keyword \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_color_quote \"#"(get_color light)"\"" >> $fish_theme
    echo "set -g fish_color_redirection \"#"(get_color dark)"\"" >> $fish_theme
    echo "set -g fish_color_end \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_color_error \"#"(get_color error)"\"" >> $fish_theme
    echo "set -g fish_color_selection \"#"(get_color dark)"\"" >> $fish_theme
    echo "set -g fish_color_search_match \"#"(get_color light)"\"" >> $fish_theme
    echo "set -g fish_color_operator \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_color_escape \"#"(get_color light)"\"" >> $fish_theme
    echo "set -g fish_color_cwd \"#"(get_color light)"\"" >> $fish_theme
    echo "set -g fish_color_user \"#"(get_color fg)"\"" >> $fish_theme
    echo "set -g fish_color_autosuggestion \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_color_param \"#"(get_color fg)"\"" >> $fish_theme
    echo "set -g fish_color_option \"#"(get_color fg)"\"" >> $fish_theme
    echo "set -g fish_pager_color_completion \"#"(get_color fg)"\"" >> $fish_theme
    echo "set -g fish_pager_color_description \"#"(get_color medium)"\"" >> $fish_theme
    echo "set -g fish_pager_color_prefix \"#"(get_color light)"\"" >> $fish_theme
    echo "set -g fish_pager_color_progress \"#"(get_color light)"\"" >> $fish_theme

    log_success "Fish theme: $fish_theme"

    # Source the theme immediately if we're in fish
    source $fish_theme 2>/dev/null
    log_success "Fish colors applied"
end

# Update Neovim colorscheme - creates a full colorscheme at lua/themes/current.lua
function apply_nvim
    set -l nvim_theme "$HOME/.config/nvim/lua/themes/current.lua"

    log_info "Applying to Neovim..."

    mkdir -p (dirname $nvim_theme)

    # Generate a complete colorscheme file
    echo "-- Theme: $THEME_NAME - Auto-generated by theme-apply.fish" > $nvim_theme
    echo "-- Usage: require('themes.current').setup()" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "local M = {}" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "local colors = {" >> $nvim_theme
    echo "    bg = \"#"(get_color bg)"\"," >> $nvim_theme
    echo "    fg = \"#"(get_color fg)"\"," >> $nvim_theme
    echo "    dark = \"#"(get_color dark)"\"," >> $nvim_theme
    echo "    medium = \"#"(get_color medium)"\"," >> $nvim_theme
    echo "    light = \"#"(get_color light)"\"," >> $nvim_theme
    echo "    accent = \"#"(get_color accent)"\"," >> $nvim_theme
    echo "    surface = \"#"(get_color surface)"\"," >> $nvim_theme
    echo "    error = \"#"(get_color error)"\"," >> $nvim_theme
    echo "    warning = \"#"(get_color warning)"\"," >> $nvim_theme
    echo "    success = \"#"(get_color success)"\"," >> $nvim_theme
    echo "    black = \"#"(get_color black)"\"," >> $nvim_theme
    echo "    red = \"#"(get_color red)"\"," >> $nvim_theme
    echo "    green = \"#"(get_color green)"\"," >> $nvim_theme
    echo "    yellow = \"#"(get_color yellow)"\"," >> $nvim_theme
    echo "    blue = \"#"(get_color blue)"\"," >> $nvim_theme
    echo "    magenta = \"#"(get_color magenta)"\"," >> $nvim_theme
    echo "    cyan = \"#"(get_color cyan)"\"," >> $nvim_theme
    echo "    white = \"#"(get_color white)"\"," >> $nvim_theme
    echo "}" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "M.colors = colors" >> $nvim_theme
    echo "M.name = \"$THEME_NAME\"" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "function M.setup()" >> $nvim_theme
    echo "    vim.cmd('hi clear')" >> $nvim_theme
    echo "    if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end" >> $nvim_theme
    echo "    vim.o.background = 'dark'" >> $nvim_theme
    echo "    vim.o.termguicolors = true" >> $nvim_theme
    echo "    vim.g.colors_name = 'current'" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- Editor" >> $nvim_theme
    echo "    hi('Normal', { fg = colors.fg, bg = colors.bg })" >> $nvim_theme
    echo "    hi('NormalFloat', { fg = colors.fg, bg = colors.dark })" >> $nvim_theme
    echo "    hi('FloatBorder', { fg = colors.medium, bg = colors.dark })" >> $nvim_theme
    echo "    hi('LineNr', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('CursorLine', { bg = colors.dark })" >> $nvim_theme
    echo "    hi('CursorLineNr', { fg = colors.fg, bold = true })" >> $nvim_theme
    echo "    hi('Visual', { bg = colors.medium })" >> $nvim_theme
    echo "    hi('Search', { fg = colors.bg, bg = colors.light })" >> $nvim_theme
    echo "    hi('IncSearch', { fg = colors.bg, bg = colors.warning })" >> $nvim_theme
    echo "    hi('MatchParen', { fg = colors.fg, bg = colors.medium, bold = true })" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- Syntax" >> $nvim_theme
    echo "    hi('Comment', { fg = colors.medium, italic = true })" >> $nvim_theme
    echo "    hi('Constant', { fg = colors.light })" >> $nvim_theme
    echo "    hi('String', { fg = colors.light })" >> $nvim_theme
    echo "    hi('Identifier', { fg = colors.fg })" >> $nvim_theme
    echo "    hi('Function', { fg = colors.fg, bold = true })" >> $nvim_theme
    echo "    hi('Statement', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('Keyword', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('PreProc', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('Type', { fg = colors.light })" >> $nvim_theme
    echo "    hi('Special', { fg = colors.fg })" >> $nvim_theme
    echo "    hi('Error', { fg = colors.error })" >> $nvim_theme
    echo "    hi('Todo', { fg = colors.bg, bg = colors.warning, bold = true })" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- Treesitter" >> $nvim_theme
    echo "    hi('@variable', { fg = colors.fg })" >> $nvim_theme
    echo "    hi('@function', { fg = colors.fg, bold = true })" >> $nvim_theme
    echo "    hi('@function.call', { fg = colors.fg })" >> $nvim_theme
    echo "    hi('@keyword', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('@string', { fg = colors.light })" >> $nvim_theme
    echo "    hi('@number', { fg = colors.light })" >> $nvim_theme
    echo "    hi('@boolean', { fg = colors.light })" >> $nvim_theme
    echo "    hi('@operator', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('@punctuation.delimiter', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('@punctuation.bracket', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('@property', { fg = colors.fg })" >> $nvim_theme
    echo "    hi('@tag', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('@attribute', { fg = colors.medium })" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- UI elements" >> $nvim_theme
    echo "    hi('StatusLine', { fg = colors.fg, bg = colors.dark })" >> $nvim_theme
    echo "    hi('StatusLineNC', { fg = colors.medium, bg = colors.dark })" >> $nvim_theme
    echo "    hi('VertSplit', { fg = colors.medium })" >> $nvim_theme
    echo "    hi('Pmenu', { fg = colors.fg, bg = colors.dark })" >> $nvim_theme
    echo "    hi('PmenuSel', { fg = colors.bg, bg = colors.light })" >> $nvim_theme
    echo "    hi('TabLine', { fg = colors.medium, bg = colors.dark })" >> $nvim_theme
    echo "    hi('TabLineSel', { fg = colors.fg, bg = colors.bg })" >> $nvim_theme
    echo "    hi('TabLineFill', { bg = colors.dark })" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- Diagnostics" >> $nvim_theme
    echo "    hi('DiagnosticError', { fg = colors.error })" >> $nvim_theme
    echo "    hi('DiagnosticWarn', { fg = colors.warning })" >> $nvim_theme
    echo "    hi('DiagnosticInfo', { fg = colors.light })" >> $nvim_theme
    echo "    hi('DiagnosticHint', { fg = colors.medium })" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "    -- Git" >> $nvim_theme
    echo "    hi('DiffAdd', { fg = colors.success })" >> $nvim_theme
    echo "    hi('DiffChange', { fg = colors.warning })" >> $nvim_theme
    echo "    hi('DiffDelete', { fg = colors.error })" >> $nvim_theme
    echo "end" >> $nvim_theme
    echo "" >> $nvim_theme
    echo "return M" >> $nvim_theme

    log_success "Neovim theme: $nvim_theme"
    log_info "In init.lua use: require('themes.current').setup()"
end

# Update Fuzzel launcher
function apply_fuzzel
    set -l fuzzel_config "$HOME/.config/fuzzel/fuzzel.ini"

    if not test -f $fuzzel_config
        log_warn "Fuzzel config not found, skipping"
        return
    end

    log_info "Applying to Fuzzel..."

    # Update colors section
    sed -i "/^\[colors\]/,/^\[/ {
        s/^background = .*/background = "(get_color bg)"ee/
        s/^text = .*/text = "(get_color fg)"ff/
        s/^match = .*/match = "(get_color light)"ff/
        s/^selection = .*/selection = "(get_color dark)"ff/
        s/^selection-text = .*/selection-text = "(get_color light)"ff/
        s/^border = .*/border = "(get_color medium)"ff/
        s/^separator = .*/separator = "(get_color dark)"ff/
    }" $fuzzel_config

    log_success "Fuzzel config updated"
end

# Update Rofi - creates a gruvbox-style theme with our colors
function apply_rofi
    set -l rofi_dir "$HOME/.config/rofi"
    set -l themes_dir "$rofi_dir/themes"
    set -l current_theme "$themes_dir/current.rasi"

    if not test -d $rofi_dir
        log_warn "Rofi config not found, skipping"
        return
    end

    log_info "Applying to Rofi..."
    mkdir -p $themes_dir

    # Create a full theme file (gruvbox-style structure with our colors)
    echo '/* Theme: '$THEME_NAME' - Auto-generated by theme-apply.fish
   Based on gruvbox-dark-hard structure */

* {
    highlight: bold italic;
    scrollbar: true;

    /* Theme colors */
    theme-bg0:      #'(get_color bg)';
    theme-bg1:      #'(get_color dark)';
    theme-bg2:      #'(get_color medium)';
    theme-fg0:      #'(get_color fg)';
    theme-fg1:      #'(get_color fg)';
    theme-accent:   #'(get_color light)';
    theme-error:    #'(get_color error)';
    theme-warning:  #'(get_color warning)';
    theme-gray:     #'(get_color medium)';

    /* Applied colors */
    background:                  @theme-bg0;
    background-color:            @background;
    foreground:                  @theme-fg1;
    border-color:                @theme-gray;
    separatorcolor:              @border-color;
    scrollbar-handle:            @border-color;

    normal-background:           @background;
    normal-foreground:           @foreground;
    alternate-normal-background: @background;
    alternate-normal-foreground: @foreground;
    selected-normal-background:  @theme-bg2;
    selected-normal-foreground:  @theme-fg0;

    active-background:           @theme-accent;
    active-foreground:           @background;
    alternate-active-background: @active-background;
    alternate-active-foreground: @active-foreground;
    selected-active-background:  @theme-warning;
    selected-active-foreground:  @active-foreground;

    urgent-background:           @theme-error;
    urgent-foreground:           @background;
    alternate-urgent-background: @urgent-background;
    alternate-urgent-foreground: @urgent-foreground;
    selected-urgent-background:  @theme-error;
    selected-urgent-foreground:  @urgent-foreground;
}

@import "gruvbox-common"' > $current_theme

    log_success "Rofi theme: $current_theme"

    # Update config.rasi to use our theme
    set -l config_file "$rofi_dir/config.rasi"
    if test -f $config_file
        # Replace any @theme line with our theme
        sed -i 's|^@theme .*|@theme "~/.config/rofi/themes/current.rasi"|' $config_file
        sed -i 's|^//@theme|// @theme|' $config_file
        log_success "Updated config.rasi to use current theme"
    end
end

# Update Tmux - creates a current.tmux theme file
function apply_tmux
    set -l tmux_theme "$HOME/.tmux/themes/current.tmux"

    log_info "Applying to Tmux..."

    mkdir -p (dirname $tmux_theme)

    echo "# Theme: $THEME_NAME - Auto-generated by theme-apply.fish" > $tmux_theme
    echo "" >> $tmux_theme
    echo "# Colors:" >> $tmux_theme
    echo "#   bg:      #"(get_color bg) >> $tmux_theme
    echo "#   fg:      #"(get_color fg) >> $tmux_theme
    echo "#   dark:    #"(get_color dark) >> $tmux_theme
    echo "#   medium:  #"(get_color medium) >> $tmux_theme
    echo "#   light:   #"(get_color light) >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Status bar" >> $tmux_theme
    echo "set -g status-style bg=default" >> $tmux_theme
    echo "set -g status-style fg='#"(get_color fg)"'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Window status" >> $tmux_theme
    echo "setw -g window-status-current-style 'fg=#"(get_color light)",bg=#"(get_color dark)"'" >> $tmux_theme
    echo "setw -g window-status-style 'fg=#"(get_color medium)",bg=default'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Pane borders" >> $tmux_theme
    echo "set -g pane-border-style 'fg=#"(get_color dark)"'" >> $tmux_theme
    echo "set -g pane-active-border-style 'fg=#"(get_color light)"'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Window background" >> $tmux_theme
    echo "setw -g window-style 'bg=#"(get_color dark)"'" >> $tmux_theme
    echo "setw -g window-active-style 'bg=#"(get_color bg)"'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Message/command style" >> $tmux_theme
    echo "set -g message-style 'fg=#"(get_color bg)",bg=#"(get_color light)"'" >> $tmux_theme
    echo "set -g message-command-style 'fg=#"(get_color bg)",bg=#"(get_color light)"'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Mode style (copy mode, etc)" >> $tmux_theme
    echo "set -g mode-style 'fg=#"(get_color bg)",bg=#"(get_color light)"'" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Clock" >> $tmux_theme
    echo "set -g clock-mode-colour '#"(get_color light)"'" >> $tmux_theme
    echo "set -g clock-mode-style 24" >> $tmux_theme
    echo "" >> $tmux_theme
    echo "# Status bar content" >> $tmux_theme
    echo "set -g status-right '#[fg=#"(get_color light)",bg=#"(get_color dark)"] %H:%M #[fg=#"(get_color medium)"] %y.%m.%d '" >> $tmux_theme
    echo "set-window-option -g window-status-format '#[fg=#"(get_color medium)",bg=default] #I #[fg=#"(get_color medium)",bg=#"(get_color dark)"] #W '" >> $tmux_theme
    echo "set-window-option -g window-status-current-format '#[fg=#"(get_color light)",bg=#"(get_color dark)"] #I #[fg=#"(get_color fg)",bg=#"(get_color dark)"] #W '" >> $tmux_theme

    log_success "Tmux theme: $tmux_theme"

    # Update .tmux.conf to source current theme if it doesn't already
    set -l tmux_conf "$HOME/.tmux.conf"
    if test -f $tmux_conf
        if not grep -q 'current.tmux' $tmux_conf
            log_warn "Add to ~/.tmux.conf: source-file \"\$HOME/.tmux/themes/current.tmux\""
        else
            log_success "Tmux config already sources current.tmux"
        end
    end

    # Reload tmux if running
    if test -n "$TMUX"
        tmux source-file $tmux_conf 2>/dev/null
        log_success "Tmux reloaded"
    end
end

# Update GTK colors (gtk-3.0 and gtk-4.0)
function apply_gtk
    log_info "Applying to GTK..."

    for gtk_ver in 3.0 4.0
        set -l colors_file "$HOME/.config/gtk-$gtk_ver/colors.css"

        if not test -f $colors_file
            log_warn "GTK $gtk_ver colors.css not found, skipping"
            continue
        end

        # Update colors in Breeze-style format
        sed -i 's/@define-color borders_breeze #[0-9a-fA-F]\{6\}/@define-color borders_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color content_view_bg_breeze #[0-9a-fA-F]\{6\}/@define-color content_view_bg_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_base_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_base_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_bg_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_fg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_fg_color_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_text_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_text_color_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_selected_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_selected_bg_color_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color theme_selected_fg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_selected_fg_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_hovering_selected_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_hovering_selected_bg_color_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color link_color_breeze #[0-9a-fA-F]\{6\}/@define-color link_color_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color tooltip_background_breeze #[0-9a-fA-F]\{6\}/@define-color tooltip_background_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color tooltip_text_breeze #[0-9a-fA-F]\{6\}/@define-color tooltip_text_breeze #'(get_color fg)'/' $colors_file

        # Update button backgrounds
        sed -i 's/@define-color theme_button_background_normal_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_background_normal_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_button_foreground_normal_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_foreground_normal_breeze #'(get_color fg)'/' $colors_file

        # Update header/titlebar
        sed -i 's/@define-color theme_header_background_breeze #[0-9a-fA-F]\{6\}/@define-color theme_header_background_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_header_foreground_breeze #[0-9a-fA-F]\{6\}/@define-color theme_header_foreground_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_titlebar_background_breeze #[0-9a-fA-F]\{6\}/@define-color theme_titlebar_background_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_titlebar_foreground_breeze #[0-9a-fA-F]\{6\}/@define-color theme_titlebar_foreground_breeze #'(get_color fg)'/' $colors_file

        # Update focus/decoration colors
        sed -i 's/@define-color theme_button_decoration_focus_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_decoration_focus_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color theme_button_decoration_hover_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_decoration_hover_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color theme_view_active_decoration_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_view_active_decoration_color_breeze #'(get_color light)'/' $colors_file
        sed -i 's/@define-color theme_view_hover_decoration_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_view_hover_decoration_color_breeze #'(get_color light)'/' $colors_file

        # Update warning/error/success
        sed -i 's/@define-color warning_color_breeze #[0-9a-fA-F]\{6\}/@define-color warning_color_breeze #'(get_color warning)'/' $colors_file
        sed -i 's/@define-color error_color_breeze #[0-9a-fA-F]\{6\}/@define-color error_color_breeze #'(get_color error)'/' $colors_file
        sed -i 's/@define-color success_color_breeze #[0-9a-fA-F]\{6\}/@define-color success_color_breeze #'(get_color success)'/' $colors_file

        # Update unfocused/backdrop colors (window not focused)
        sed -i 's/@define-color theme_unfocused_base_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_base_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_bg_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_fg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_fg_color_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_text_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_text_color_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_view_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_view_bg_color_breeze #'(get_color bg)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_view_text_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_view_text_color_breeze #'(get_color medium)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_selected_bg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_selected_bg_color_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_selected_bg_color_alt_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_selected_bg_color_alt_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_unfocused_selected_fg_color_breeze #[0-9a-fA-F]\{6\}/@define-color theme_unfocused_selected_fg_color_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color unfocused_borders_breeze #[0-9a-fA-F]\{6\}/@define-color unfocused_borders_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color unfocused_insensitive_borders_breeze #[0-9a-fA-F]\{6\}/@define-color unfocused_insensitive_borders_breeze #'(get_color dark)'/' $colors_file

        # Update backdrop colors
        sed -i 's/@define-color theme_header_background_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_header_background_backdrop_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_header_foreground_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_header_foreground_backdrop_breeze #'(get_color fg)'/' $colors_file
        sed -i 's/@define-color theme_titlebar_background_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_titlebar_background_backdrop_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_titlebar_foreground_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_titlebar_foreground_backdrop_breeze #'(get_color medium)'/' $colors_file
        sed -i 's/@define-color theme_button_background_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_background_backdrop_breeze #'(get_color dark)'/' $colors_file
        sed -i 's/@define-color theme_button_foreground_backdrop_breeze #[0-9a-fA-F]\{6\}/@define-color theme_button_foreground_backdrop_breeze #'(get_color fg)'/' $colors_file

        # Update header comment
        sed -i '1s/.*/\/* Theme: '$THEME_NAME' - Auto-generated by theme-apply.fish *\//' $colors_file

        log_success "GTK $gtk_ver colors updated"
    end

    log_warn "Restart GTK apps (pcmanfm, nemo, etc.) to see changes"
end

# Update hyprlock - creates themed hyprlock config
function apply_hyprlock
    set -l hyprlock_config "$HOME/.config/hypr/hyprlock.conf"

    log_info "Applying to hyprlock..."

    # Create/update the hyprlock config with theme colors
    echo "# Hyprlock configuration with theme integration" > $hyprlock_config
    echo "# Theme: $THEME_NAME - Auto-generated by theme-apply.fish" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "# Source theme colors (will be available as \$theme_* variables)" >> $hyprlock_config
    echo "source = ~/.config/hypr/themes/current.conf" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "# Font configuration" >> $hyprlock_config
    echo "\$font_family = Inter V" >> $hyprlock_config
    echo "\$font_family_clock = Inter V" >> $hyprlock_config
    echo "\$font_material_symbols = Material Symbols Rounded" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "# Derived colors from theme" >> $hyprlock_config
    echo "\$text_color = \$theme_fg" >> $hyprlock_config
    echo "\$entry_background_color = \$theme_bg" >> $hyprlock_config
    echo "\$entry_border_color = \$theme_medium" >> $hyprlock_config
    echo "\$entry_color = \$theme_fg" >> $hyprlock_config
    echo "\$ring_color = \$theme_medium" >> $hyprlock_config
    echo "\$ring_ver_color = \$theme_light" >> $hyprlock_config
    echo "\$ring_wrong_color = rgb("(get_color error)")  # Error color from $THEME_NAME" >> $hyprlock_config
    echo "\$ring_clear_color = \$theme_dark" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "background {" >> $hyprlock_config
    echo "    path = screenshot" >> $hyprlock_config
    echo "    blur_passes = 3" >> $hyprlock_config
    echo "    blur_size = 8" >> $hyprlock_config
    echo "    noise = 0.0117" >> $hyprlock_config
    echo "    contrast = 0.8916" >> $hyprlock_config
    echo "    brightness = 0.8172" >> $hyprlock_config
    echo "    vibrancy = 0.1696" >> $hyprlock_config
    echo "    vibrancy_darkness = 0.0" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "input-field {" >> $hyprlock_config
    echo "    size = 250, 50" >> $hyprlock_config
    echo "    outline_thickness = 2" >> $hyprlock_config
    echo "    dots_size = 0.33" >> $hyprlock_config
    echo "    dots_spacing = 0.15" >> $hyprlock_config
    echo "    dots_center = true" >> $hyprlock_config
    echo "    outer_color = \$ring_color" >> $hyprlock_config
    echo "    inner_color = \$entry_background_color" >> $hyprlock_config
    echo "    font_color = \$entry_color" >> $hyprlock_config
    echo "    fade_on_empty = true" >> $hyprlock_config
    echo "    fade_timeout = 2000" >> $hyprlock_config
    echo "    placeholder_text = <i>Enter password</i>" >> $hyprlock_config
    echo "    hide_input = false" >> $hyprlock_config
    echo "    rounding = 10" >> $hyprlock_config
    echo "    check_color = \$ring_ver_color" >> $hyprlock_config
    echo "    fail_color = \$ring_wrong_color" >> $hyprlock_config
    echo "    capslock_color = \$ring_clear_color" >> $hyprlock_config
    echo "    numlock_color = -1" >> $hyprlock_config
    echo "    bothlock_color = -1" >> $hyprlock_config
    echo "    invert_numlock = false" >> $hyprlock_config
    echo "    swap_font_capslock = false" >> $hyprlock_config
    echo "    position = 0, 20" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = center" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "label {" >> $hyprlock_config
    echo "    text = \$TIME" >> $hyprlock_config
    echo "    shadow_passes = 1" >> $hyprlock_config
    echo "    shadow_boost = 0.5" >> $hyprlock_config
    echo "    color = \$text_color" >> $hyprlock_config
    echo "    font_size = 65" >> $hyprlock_config
    echo "    font_family = \$font_family_clock" >> $hyprlock_config
    echo "    position = 0, 300" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = center" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "label {" >> $hyprlock_config
    echo "    text = Hello, \$USER" >> $hyprlock_config
    echo "    shadow_passes = 1" >> $hyprlock_config
    echo "    shadow_boost = 0.5" >> $hyprlock_config
    echo "    color = \$text_color" >> $hyprlock_config
    echo "    font_size = 20" >> $hyprlock_config
    echo "    font_family = \$font_family" >> $hyprlock_config
    echo "    position = 0, 240" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = center" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "label {" >> $hyprlock_config
    echo "    text = lock" >> $hyprlock_config
    echo "    shadow_passes = 1" >> $hyprlock_config
    echo "    shadow_boost = 0.5" >> $hyprlock_config
    echo "    color = \$text_color" >> $hyprlock_config
    echo "    font_size = 21" >> $hyprlock_config
    echo "    font_family = \$font_material_symbols" >> $hyprlock_config
    echo "    position = 0, 65" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = bottom" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "label {" >> $hyprlock_config
    echo "    text = Session Locked" >> $hyprlock_config
    echo "    shadow_passes = 1" >> $hyprlock_config
    echo "    shadow_boost = 0.5" >> $hyprlock_config
    echo "    color = \$text_color" >> $hyprlock_config
    echo "    font_size = 14" >> $hyprlock_config
    echo "    font_family = \$font_family" >> $hyprlock_config
    echo "    position = 0, 45" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = bottom" >> $hyprlock_config
    echo "}" >> $hyprlock_config
    echo "" >> $hyprlock_config
    echo "label {" >> $hyprlock_config
    echo "    text = cmd[update:1000] date +\"%A, %B %d\"" >> $hyprlock_config
    echo "    shadow_passes = 1" >> $hyprlock_config
    echo "    shadow_boost = 0.5" >> $hyprlock_config
    echo "    color = \$theme_light" >> $hyprlock_config
    echo "    font_size = 18" >> $hyprlock_config
    echo "    font_family = \$font_family" >> $hyprlock_config
    echo "    position = 0, 150" >> $hyprlock_config
    echo "    halign = center" >> $hyprlock_config
    echo "    valign = center" >> $hyprlock_config
    echo "}" >> $hyprlock_config

    log_success "hyprlock config updated: $hyprlock_config"
end
    set -l wlogout_style "$HOME/.config/wlogout/style.css"

    if not test -f $wlogout_style
        log_warn "wlogout style not found, skipping"
        return
    end

    log_info "Applying to wlogout..."

    # Similar to waybar, inject CSS variables
    set -l css_vars "/* Theme: $THEME_NAME - Auto-generated */
:root {
  --bg: #"(get_color bg)";
  --fg: #"(get_color fg)";
  --dark: #"(get_color dark)";
  --light: #"(get_color light)";
  --accent: #"(get_color accent)";
}
"

    if grep -q ':root {' $wlogout_style
        sed -i '/:root {/,/^}/d' $wlogout_style
        sed -i '/Theme:.*Auto-generated/d' $wlogout_style
    end

    echo "$css_vars" | cat - $wlogout_style > /tmp/wlogout_style_tmp && mv /tmp/wlogout_style_tmp $wlogout_style

    log_success "wlogout style updated"
end

# Main function
function main
    # Parse arguments
    if test (count $argv) -eq 0
        show_help
        return 1
    end

    switch $argv[1]
        case --help -h
            show_help
            return 0
        case --list -l
            list_themes
            return 0
        case --current -c
            show_current
            return $status
        case '--*'
            log_error "Unknown option: $argv[1]"
            show_help
            return 1
    end

    set -g THEME_NAME $argv[1]
    set -l theme_file "$THEMES_DIR/$THEME_NAME.conf"

    if not test -f $theme_file
        log_error "Theme not found: $THEME_NAME"
        echo "Available themes:"
        list_themes
        return 1
    end

    echo ""
    log_info "Applying theme: $THEME_NAME"
    echo ""

    # Load theme colors
    if not load_theme $theme_file
        return 1
    end

    # Apply to all applications
    apply_hyprland
    apply_foot
    apply_mako
    apply_waybar
    apply_starship
    apply_fish
    apply_nvim
    apply_fuzzel
    apply_rofi
    apply_tmux
    apply_gtk
    apply_wlogout
    apply_hyprlock

    # Save current theme
    echo $THEME_NAME > $CURRENT_THEME_FILE

    echo ""
    log_success "Theme '$THEME_NAME' applied successfully!"
    echo ""
    echo "Some changes may require:"
    echo "  - Restart your terminal for full effect"
    echo "  - Run 'source ~/.config/fish/conf.d/theme.fish' for fish colors"
    echo "  - Restart nvim for editor colors"
end

main $argv
