# ~/.config/fuzzel/fuzzel.ini

[main]
font = JetBrainsMono Nerd Font:size=14
prompt = "❯ "
dpi-aware = true
lines = 10
horizontal-pad = 60
vertical-pad = 60
inner-pad = 12
icon-theme = "Papirus-Dark"
terminal = foot
anchor = center
width = 50
line-height = 28
exit-on-keyboard-focus-loss = true
layer = overlay

[colors]
background = 1A1412ee
text = C3A995ff
match = AB947Eff
selection = 593D3Bff
selection-text = AB947Eff
border = 8A7968ff
separator = 593D3Bff

[border]
width = 2
radius = 6

[scroll]
indicator = true
indicator-position = right
