[mgr]
show_hidden = true
sort_by = "mtime"
sort_reverse = true

[plugin]
preloaders = [
  { mime = "image/*", run = "image" },
]

[opener]
# Images
image_view = [
  { run = 'imv "$@"', orphan = true, desc = "View Image (imv)" }
]

# Video / Audio
media_view = [
  { run = 'mpv "$@"', orphan = true, desc = "Play Media (mpv)" }
]

# PDFs
pdf_view = [
  { run = 'mupdf "$@"', orphan = true, desc = "View PDF (mupdf)" }
]

# Office
office_write = [
  { run = 'libreoffice --writer "$@"', orphan = true, desc = "Open in LibreOffice Writer" },
]
office_calc = [
  { run = 'libreoffice --calc "$@"', orphan = true, desc = "Open in LibreOffice Calc" },
]

# Archives
extract = [
  { run = 'unar "$@"', desc = "Extract here (unar)" },
  { run = 'unzip "$@"', desc = "Extract here (unzip)" },
]

# Text
text_edit = [
  { run = 'nvim "$@"', block = true, desc = "Edit Text (Neovim)" }
]
text_view = [
  { run = 'bat --paging=always "$@"', block = true, desc = "View Text (bat)" },
  { run = 'less "$@"', block = true }
]

[open]
rules = [
  # Images
  { mime = "image/*", use = "image_view" },
  
  # Videos
  { mime = "video/*", use = "media_view" },
  
  # Audio
  { mime = "audio/*", use = "media_view" },
  
  # PDFs
  { mime = "application/pdf", use = "pdf_view" },
  
  # Office
  { url = "*.docx", use = "office_write" },
  { url = "*.doc", use = "office_write" },
  { url = "*.odt", use = "office_write" },
  { url = "*.csv", use = "office_calc" },
  { url = "*.xlsx", use = "office_calc" },
  { url = "*.xls", use = "office_calc" },
  { url = "*.ods", use = "office_calc" },

  # Archives
  { mime = "application/zip", use = "extract" },
  { mime = "application/x-tar", use = "extract" },
  { mime = "application/x-7z-compressed", use = "extract" },
  { mime = "application/x-rar", use = "extract" },
  { url = "*.zip", use = "extract" },
  { url = "*.tar*", use = "extract" },
  { url = "*.7z", use = "extract" },
  { url = "*.rar", use = "extract" },

  # Text files
  { mime = "text/*", use = "text_edit" },
  { url = "*.md", use = "text_edit" },
  { url = "*.toml", use = "text_edit" },
  { url = "*.json", use = "text_edit" },
  { url = "*.yaml", use = "text_edit" },
  { url = "*.yml", use = "text_edit" }
]
