[main]
font=CaskaydiaCove Nerd Font:size=13
dpi-aware=no
bold-text-in-bright=no
pad=10x8

# [key-bindings]
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[colors-dark]
foreground=dcd7ba
background=1f1f28
regular0=1f1f28 # black
regular1=ff5d62 # red
regular2=98bb6c # green
regular3=e6c384 # yellow
regular4=7fb4ca # blue
regular5=957fb8 # magenta
regular6=7aa89f # cyan
regular7=dcd7ba # white
bright0=2a2a37 # bright black
bright1=ff5d62 # bright red
bright2=98bb6c # bright green
bright3=e6c384 # bright yellow
bright4=7fb4ca # bright blue
bright5=957fb8 # bright magenta
bright6=7aa89f # bright cyan
bright7=dcd7ba # bright white
16=de935f
17=a3685a
18=282a2e
19=373b41
20=b4b7b4
21=e0e0e0
