[main]
font=CaskaydiaCove Nerd Font:size=13
dpi-aware=no
bold-text-in-bright=no
pad=10x8

# [key-bindings]
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[colors-dark]
foreground=C3A995
background=1A1412
regular0=1A1412 # black
regular1=CC6666 # red
regular2=8A9A6E # green
regular3=D4A36A # yellow
regular4=8A7968 # blue
regular5=9A7A8A # magenta
regular6=AB947E # cyan
regular7=C3A995 # white
bright0=593D3B # bright black
bright1=D48585 # bright red
bright2=9DAD82 # bright green
bright3=E0B580 # bright yellow
bright4=9A8978 # bright blue
bright5=AD8D9D # bright magenta
bright6=BDA790 # bright cyan
bright7=D4C4B4 # bright white
16=de935f
17=a3685a
18=282a2e
19=373b41
20=b4b7b4
21=e0e0e0
