exec-once = hyrpctl dispatch dpms on

# notifications and bar
exec-once = mako
exec-once = waybar

# clipboard 
exec-once = clipse -listen 

# use kitty for floating terminal
windowrulev2 = float,class:^(kitty)$
windowrulev2 = size 622 652,class:^(kitty)$

# core components
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = swayidle -w 
