# bar, wallpaper
# exec-once = waybar

exec-once = hyrpctl dispatch dpms on

# audio 


# notifications
#exec-once = mako
exec-once = ags

# clipboard
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
exec-once = /usr/bin/clipster -d

# core components
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
#exec-once = hypridle
exec-once = swayidle -w 
#exec-once = ulauncher --hide-window
