exec-once = hyprctl dispatch dpms on

# notifications and bar
exec-once = mako
exec-once = waybar

# wallpaper daemon
exec-once = hyprpaper

# clipboard 
exec-once = wl-paste --watch cliphist store

# use kitty for floating terminal
windowrule = float on, match:class ^(kitty)$
windowrule = float on, match:class com.gabm.satty
windowrule = size 1400 900, match:class ^(kitty)$

# float nautilus preview
windowrule = float on, match:class ^(org.gnome.NautilusPreviewer)$
windowrule = center on, match:class ^(org.gnome.NautilusPreviewer)$

# core components
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = /usr/lib/polkit-kde-authentication-agent-1
# use hypridle instead of swayidle (fixes "lock died" error on resume)
exec-once = hypridle 
