# Theme: hamblue - Auto-generated by theme-apply.fish

# LS_COLORS
set -x LS_COLORS "di=38;2;184;219;217:fi=38;2;244;244;249:ln=38;2;184;219;217:ex=38;2;152;195;121"

# Fish colors (using -g to override fish_frozen_theme)
set -g fish_color_normal "#F4F4F9"
set -g fish_color_command "#577787"
set -g fish_color_comment "#2F4550"
set -g fish_color_keyword "#577787"
set -g fish_color_quote "#B8DBD9"
set -g fish_color_redirection "#2F4550"
set -g fish_color_end "#577787"
set -g fish_color_error "#E06C75"
set -g fish_color_selection "#2F4550"
set -g fish_color_search_match "#B8DBD9"
set -g fish_color_operator "#577787"
set -g fish_color_escape "#B8DBD9"
set -g fish_color_cwd "#B8DBD9"
set -g fish_color_user "#F4F4F9"
set -g fish_color_autosuggestion "#577787"
set -g fish_color_param "#F4F4F9"
set -g fish_color_option "#F4F4F9"
set -g fish_pager_color_completion "#F4F4F9"
set -g fish_pager_color_description "#577787"
set -g fish_pager_color_prefix "#B8DBD9"
set -g fish_pager_color_progress "#B8DBD9"
