# Theme: serene-nature - Auto-generated by theme-apply.fish

# LS_COLORS
set -x LS_COLORS "di=38;2;204;227;222:fi=38;2;246;255;248:ln=38;2;204;227;222:ex=38;2;164;195;178"

# Fish colors (using -g to override fish_frozen_theme)
set -g fish_color_normal "#F6FFF8"
set -g fish_color_command "#A4C3B2"
set -g fish_color_comment "#6B9080"
set -g fish_color_keyword "#A4C3B2"
set -g fish_color_quote "#CCE3DE"
set -g fish_color_redirection "#6B9080"
set -g fish_color_end "#A4C3B2"
set -g fish_color_error "#E06C75"
set -g fish_color_selection "#6B9080"
set -g fish_color_search_match "#CCE3DE"
set -g fish_color_operator "#A4C3B2"
set -g fish_color_escape "#CCE3DE"
set -g fish_color_cwd "#CCE3DE"
set -g fish_color_user "#F6FFF8"
set -g fish_color_autosuggestion "#A4C3B2"
set -g fish_color_param "#F6FFF8"
set -g fish_color_option "#F6FFF8"
set -g fish_pager_color_completion "#F6FFF8"
set -g fish_pager_color_description "#A4C3B2"
set -g fish_pager_color_prefix "#CCE3DE"
set -g fish_pager_color_progress "#CCE3DE"
