# Theme: cozy-cabin - Auto-generated by theme-apply.fish

# LS_COLORS
set -x LS_COLORS "di=38;2;171;148;126:fi=38;2;195;169;149:ln=38;2;171;148;126:ex=38;2;138;154;110"

# Fish colors (using -g to override fish_frozen_theme)
set -g fish_color_normal "#C3A995"
set -g fish_color_command "#8A7968"
set -g fish_color_comment "#593D3B"
set -g fish_color_keyword "#8A7968"
set -g fish_color_quote "#AB947E"
set -g fish_color_redirection "#593D3B"
set -g fish_color_end "#8A7968"
set -g fish_color_error "#CC6666"
set -g fish_color_selection "#593D3B"
set -g fish_color_search_match "#AB947E"
set -g fish_color_operator "#8A7968"
set -g fish_color_escape "#AB947E"
set -g fish_color_cwd "#AB947E"
set -g fish_color_user "#C3A995"
set -g fish_color_autosuggestion "#8A7968"
set -g fish_color_param "#C3A995"
set -g fish_color_option "#C3A995"
set -g fish_pager_color_completion "#C3A995"
set -g fish_pager_color_description "#8A7968"
set -g fish_pager_color_prefix "#AB947E"
set -g fish_pager_color_progress "#AB947E"
