# Theme: night-owl - Auto-generated by theme-apply.fish

# LS_COLORS
set -x LS_COLORS "di=38;2;130;170;255:fi=38;2;214;222;235:ln=38;2;128;203;196:ex=38;2;173;219;103"

# Fish colors (using -g to override fish_frozen_theme)
set -g fish_color_normal "#d6deeb"
set -g fish_color_command "#7e57c2"
set -g fish_color_comment "#1d3b53"
set -g fish_color_keyword "#7e57c2"
set -g fish_color_quote "#82aaff"
set -g fish_color_redirection "#1d3b53"
set -g fish_color_end "#7e57c2"
set -g fish_color_error "#ef5350"
set -g fish_color_selection "#1d3b53"
set -g fish_color_search_match "#82aaff"
set -g fish_color_operator "#7e57c2"
set -g fish_color_escape "#82aaff"
set -g fish_color_cwd "#82aaff"
set -g fish_color_user "#d6deeb"
set -g fish_color_autosuggestion "#7e57c2"
set -g fish_color_param "#d6deeb"
set -g fish_color_option "#d6deeb"
set -g fish_pager_color_completion "#d6deeb"
set -g fish_pager_color_description "#7e57c2"
set -g fish_pager_color_prefix "#82aaff"
set -g fish_pager_color_progress "#82aaff"
