$black         = rgb(1d1f21)  # base00 - background
$darkbluegrey  = rgb(282a2e)  # base01 - dark gray/blue
$medbluegrey   = rgb(372b41)  # base02 - medium gray
$lightbluegrey = rgb(71CEAD)  # active border
$offwhite      = rgb(c5c8c6)  # base05 - soft foreground
