-- Theme: cozy-cabin - Auto-generated by theme-apply.fish
-- Usage: require('themes.current').setup()

local M = {}

local colors = {
    bg = "#1A1412",
    fg = "#C3A995",
    dark = "#593D3B",
    medium = "#8A7968",
    light = "#AB947E",
    accent = "#AB947E",
    surface = "#593D3B",
    error = "#CC6666",
    warning = "#D4A36A",
    success = "#8A9A6E",
    black = "#1A1412",
    red = "#CC6666",
    green = "#8A9A6E",
    yellow = "#D4A36A",
    blue = "#8A7968",
    magenta = "#9A7A8A",
    cyan = "#AB947E",
    white = "#C3A995",
}

M.colors = colors
M.name = "cozy-cabin"

function M.setup()
    vim.cmd('hi clear')
    if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end
    vim.o.background = 'dark'
    vim.o.termguicolors = true
    vim.g.colors_name = 'current'

    local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

    -- Editor
    hi('Normal', { fg = colors.fg, bg = colors.bg })
    hi('NormalFloat', { fg = colors.fg, bg = colors.dark })
    hi('FloatBorder', { fg = colors.medium, bg = colors.dark })
    hi('LineNr', { fg = colors.medium })
    hi('CursorLine', { bg = colors.dark })
    hi('CursorLineNr', { fg = colors.fg, bold = true })
    hi('Visual', { bg = colors.medium })
    hi('Search', { fg = colors.bg, bg = colors.light })
    hi('IncSearch', { fg = colors.bg, bg = colors.warning })
    hi('MatchParen', { fg = colors.fg, bg = colors.medium, bold = true })

    -- Syntax
    hi('Comment', { fg = colors.medium, italic = true })
    hi('Constant', { fg = colors.light })
    hi('String', { fg = colors.light })
    hi('Identifier', { fg = colors.fg })
    hi('Function', { fg = colors.fg, bold = true })
    hi('Statement', { fg = colors.medium })
    hi('Keyword', { fg = colors.medium })
    hi('PreProc', { fg = colors.medium })
    hi('Type', { fg = colors.light })
    hi('Special', { fg = colors.fg })
    hi('Error', { fg = colors.error })
    hi('Todo', { fg = colors.bg, bg = colors.warning, bold = true })

    -- Treesitter
    hi('@variable', { fg = colors.fg })
    hi('@function', { fg = colors.fg, bold = true })
    hi('@function.call', { fg = colors.fg })
    hi('@keyword', { fg = colors.medium })
    hi('@string', { fg = colors.light })
    hi('@number', { fg = colors.light })
    hi('@boolean', { fg = colors.light })
    hi('@operator', { fg = colors.medium })
    hi('@punctuation.delimiter', { fg = colors.medium })
    hi('@punctuation.bracket', { fg = colors.medium })
    hi('@property', { fg = colors.fg })
    hi('@tag', { fg = colors.medium })
    hi('@attribute', { fg = colors.medium })

    -- UI elements
    hi('StatusLine', { fg = colors.fg, bg = colors.dark })
    hi('StatusLineNC', { fg = colors.medium, bg = colors.dark })
    hi('VertSplit', { fg = colors.medium })
    hi('Pmenu', { fg = colors.fg, bg = colors.dark })
    hi('PmenuSel', { fg = colors.bg, bg = colors.light })
    hi('TabLine', { fg = colors.medium, bg = colors.dark })
    hi('TabLineSel', { fg = colors.fg, bg = colors.bg })
    hi('TabLineFill', { bg = colors.dark })

    -- Diagnostics
    hi('DiagnosticError', { fg = colors.error })
    hi('DiagnosticWarn', { fg = colors.warning })
    hi('DiagnosticInfo', { fg = colors.light })
    hi('DiagnosticHint', { fg = colors.medium })

    -- Git
    hi('DiffAdd', { fg = colors.success })
    hi('DiffChange', { fg = colors.warning })
    hi('DiffDelete', { fg = colors.error })
end

return M
