[main]
font=CaskaydiaCove Nerd Font:size=11
dpi-aware=yes
bold-text-in-bright=no
pad=10x8

# [key-bindings]
# clipboard-copy=Control+c XF86Copy
# clipboard-paste=Control+v XF86Paste

[colors-dark]
foreground=ebdbb2
background=1d2021
regular0=1d2021 # black
regular1=fb4934 # red
regular2=b8bb26 # green
regular3=fabd2f # yellow
regular4=83a598 # blue
regular5=d3869b # magenta
regular6=8ec07c # cyan
regular7=ebdbb2 # white
bright0=3c3836 # bright black
bright1=fb4934 # bright red
bright2=b8bb26 # bright green
bright3=fabd2f # bright yellow
bright4=83a598 # bright blue
bright5=d3869b # bright magenta
bright6=8ec07c # bright cyan
bright7=fbf1c7 # bright white
16=de935f
17=a3685a
18=282a2e
19=373b41
20=b4b7b4
21=e0e0e0
